name: provisionresources

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      appName:
        required: true
        type: string
      location:
        required: true
        type: string
    secrets:
      subscriptionId:
        required: true
      credentials:
        required: true

env:
  ARTIFACT_NAME: ${{ github.event.release.tag_name }}

jobs:
  provisionresources:
    name: ${{ inputs.appName }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.credentials }}

      - name: Download API
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

      - name: Download Templates
        uses: actions/download-artifact@v3
        with:
          name: deploy
          path: deploy

      - name: Provision Resources
        uses: azure/arm-deploy@v1
        with:
          failOnStdErr: false
          deploymentName: ${{ env.ARTIFACT_NAME }}
          scope: subscription
          region: ${{ inputs.location }}
          subscriptionId: ${{ secrets.subscriptionId }}
          template: deploy/main.bicep
          parameters: >
            appName=${{ inputs.appName }}
            version=${{ env.ARTIFACT_NAME }}
            environment=${{ inputs.environment }}
            location=${{ inputs.location }}

      - name: "Deploy Azure Function App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bun-fn-${{ inputs.appName }}-${{ inputs.environment }}'
          package: ${{ env.ARTIFACT_NAME }}

      - name: Logout from Azure
        uses: Azure/CLI@v1
        with:
          inlineScript:
            az logout            